set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

set(LLVM_TARGETS_TO_BUILD "RISCV;X86;AArch64" CACHE STRING "")
set(LLVM_ENABLE_PROJECTS "clang;clang-tools-extra;lld;llvm" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt" CACHE STRING "")


